# Generated by Django 3.2.15 on 2022-09-07 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Taskname', models.TextField(max_length=255)),
                ('Taskdate', models.DateTimeField(auto_now=True)),
                ('Taskstatus', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StatusDesc', models.TextField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='firstname',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastname',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.TextField(max_length=255),
        ),
    ]
