# Generated by Django 3.2.15 on 2022-09-12 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0003_auto_20220907_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='Taskdate',
            field=models.DateTimeField(),
        ),
    ]
