# Generated by Django 3.2.15 on 2022-09-12 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0004_alter_appointments_taskdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='Taskdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
