# Generated by Django 3.2.15 on 2022-09-12 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0005_alter_appointments_taskdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LikedAppointment', models.IntegerField()),
                ('LikedBy', models.IntegerField()),
            ],
        ),
    ]
