# Generated by Django 3.2.15 on 2022-09-12 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0006_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='LikedAppointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='appoinments', to='app2.appointments'),
        ),
        migrations.AlterField(
            model_name='like',
            name='LikedBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='users1', to='app2.user'),
        ),
    ]
